on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: egor-tensin/setup-gcc@v1
    - run: g++ -DTESTING sol.cpp -o sol.exe
    - run: ./sol.exe
